# generated by datamodel-codegen:
#   filename:  swagger.yaml
#   timestamp: 2024-07-09T15:55:12+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Field0(BaseModel):
    __root__: Any
