# generated by datamodel-codegen:
#   filename:  swagger.yaml
#   timestamp: 2024-07-09T19:33:12+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class AppError(BaseModel):
    code: Optional[int] = None
    reason: Optional[str] = None
    message: Optional[str] = None


class RecordReindexRequest(BaseModel):
    kind: str
    cursor: Optional[str] = None


class ReindexRecordsRequest(BaseModel):
    recordIds: List[str] = Field(..., max_items=1000, min_items=1)


class ConnectedOuterService(BaseModel):
    name: Optional[str] = None
    version: Optional[str] = None


class VersionInfo(BaseModel):
    groupId: Optional[str] = None
    artifactId: Optional[str] = None
    version: Optional[str] = None
    buildTime: Optional[str] = None
    branch: Optional[str] = None
    commitId: Optional[str] = None
    commitMessage: Optional[str] = None
    connectedOuterServices: Optional[List[ConnectedOuterService]] = None
