name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  publish:
      name: "Publish in PYPI"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Publish
          env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
          run: |
            pip3 install wheel twine
            python3 setup.py sdist bdist_wheel
            python3 -m twine check dist/*
            python3 -m twine upload --skip-existing dist/* --verbose -u ${USERNAME} -p ${PASSWORD}

